name: methylcdm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.1
  - pytorch-cuda=11.8
  - torchvision
  - pip
  - pip:
    - einops
    - einops-exts
    - pandas
    - pillow
    - tqdm
    - kornia
    - resize-right
